FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ app/
COPY tests/ tests/
COPY pyproject.toml .

CMD [ "python", "-m", "pytest", "-s", "--cov=app", "--cov-report=term-missing",  "--cov-fail-under=90", "--cov-report=html"]